### ISSUE TITLE
pycharm运行出错了。

### ISSUE THREAD

**Issue by asdaca0** [cjh4312/stock-quotes#2]
D:\anaconda\python.exe D:\Python-proj\Github\stock-quotes-main\mainwindow.py 
Traceback (most recent call last):
  File "D:\anaconda\lib\tokenize.py", line 330, in find_cookie
    line_string = line.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python-proj\Github\stock-quotes-main\mainwindow.py", line 5, in <module>
    import worldIndex,drawTimeShare,drawCandle,globalVariable,getDate,tableStock,baseInformation
  File "D:\Python-proj\Github\stock-quotes-main\tableStock.py", line 7, in <module>
    import getEastData
  File "D:\Python-proj\Github\stock-quotes-main\getEastData.py", line 7, in <module>
    import py_mini_racer
  File "D:\anaconda\lib\site-packages\py_mini_racer\__init__.py", line 1, in <module>
    from . import py_mini_racer
  File "D:\anaconda\lib\site-packages\py_mini_racer\py_mini_racer.py", line 13, in <module>
    import pkg_resources
  File "D:\anaconda\lib\site-packages\pkg_resources\__init__.py", line 74, in <module>
    from pkg_resources.extern import appdirs
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "D:\anaconda\lib\site-packages\pkg_resources\extern\__init__.py", line 52, in create_module
    return self.load_module(spec.name)
  File "D:\anaconda\lib\site-packages\pkg_resources\extern\__init__.py", line 37, in load_module
    __import__(extant)
  File "D:\anaconda\lib\site-packages\pkg_resources\_vendor\appdirs.py", line 560, in <module>
    import win32com.shell
  File "D:\anaconda\lib\site-packages\win32com\__init__.py", line 6, in <module>
    import pythoncom
  File "D:\anaconda\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "shibokensupport/signature/loader.py", line 61, in feature_imported
  File "shibokensupport/feature.py", line 137, in feature_imported
  File "shibokensupport/feature.py", line 148, in _mod_uses_pyside
  File "D:\anaconda\lib\inspect.py", line 1024, in getsource
    lines, lnum = getsourcelines(object)
  File "D:\anaconda\lib\inspect.py", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "D:\anaconda\lib\inspect.py", line 831, in findsource
    lines = linecache.getlines(file, module.__dict__)
  File "D:\anaconda\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "D:\anaconda\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
  File "D:\anaconda\lib\tokenize.py", line 394, in open
    encoding, lines = detect_encoding(buffer.readline)
  File "D:\anaconda\lib\tokenize.py", line 371, in detect_encoding
    encoding = find_cookie(first)
  File "D:\anaconda\lib\tokenize.py", line 335, in find_cookie
    raise SyntaxError(msg)
SyntaxError: invalid or missing encoding declaration for 'D:\\anaconda\\lib\\site-packages\\win32\\pywintypes39.dll'

Process finished with exit code 1

**Comment by cjh4312** [comment]
设置一下pycharm的文件编码，是utf-8吗？
